### ISSUE TITLE
Use matching context’s Xpath

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/mobile#135]
Actuellement, l'xpath n'est pas géré. 
Donc lorsque une bulle a un xpath, elle est ignorée.

**Comment by MaartenLMEM** [comment]
@JalilArfaoui @felix-lambert please can you size this feature ?

**Comment by felix-lambert** [comment]
I think it's an L because me might have to change some things in the backend. Not sure. @JalilArfaoui tell me when your available so that we can have a fast talk on this.

**Comment by JalilArfaoui** [comment]
@felix-lambert no need to alter anything on the backend side (this feature is already publicly available on extension).

The difficulty is to see if we can analyse the page content and not only the URL, as we are «outside» the browser … Do you have any clue yet ?

**Comment by felix-lambert** [comment]
Ok not yet but will check it out

**Comment by prk-dismoi** [comment]
Was discussed between @JalilArfaoui and @felix-lambert we;re adding to to do list

**Comment by felix-lambert** [comment]
Does it take time to create a specific xpath for mobile?
Some examples:
```
android.webkit.WebView
android.widget.TextView
android.widget.Image
android.view.View
android.widget.Button
```
? 

If yes I think that we might need to focus on other tickets IMHO

**Comment by JalilArfaoui** [comment]
I am not sure to understand what you mean by specific xpath for mobile … What kind of query would enable us to find a specific word in a specific DOM object in a web page rendered by Chrome ?

**Comment by MaartenLMEM** [comment]
- Feature unplugged by Felix in last version 1.0.8 (7) after meeting this issue https://github.com/dis-moi/mobile_poc/issues/200  
- Next step : Jalil will dive in this issue, verifying performance issues on mobile related to xpath matching engine "working alone" on a device.

**Comment by JalilArfaoui** [comment]
We have decided in #234  that we’re going to use specific content fields instead of technical xpath property of matching contexts. I’m closing this.
