### ISSUE TITLE
Remove `onInterrupt` in `BackgroundService`

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/mobile#227]
onInterrupt

J: À quoi sert l’évènement `EventFromAccessibilityServicePermission` déclenché au `onInterrupt` du `BackgroundService` ? 

F: Jamais réussi à le déclencher … À supprimer

J: Pareil pour sendEventFromOverlayPermission ?

F: Oui, c’est probablement du code mort

**Comment by JalilArfaoui** [comment]
Removed in #233
