### ISSUE TITLE
Launcher : clarify our app behaviour in relation with it

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/mobile#229]
J: Pourquoi est-ce que quand on change d’application, on a pas de problème à faire disparaitre la bulle, mais si on va sur le launcher on a besoin d’une détection spécifique ?

F: Comportement spécifique du launcher qui garde l’overlay apparent, mais pas au switch d’application

J: Pourquoi a-t-on besoin de gérer spécifiquement "com.google.android.inputmethod", "com.google.android.googlequicksearchbox" et "com.android.systemui" ? Que se passe-t-il si on utilise une méthode de saisie différente ?

F: Je ne l’ai pas pris en compte

**Comment by JalilArfaoui** [comment]
#233 totally changed the relation with launchers and other applications, which closes this question.
