### ISSUE TITLE
Do our matching contexts work with mobile urls that do no display www.

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/mobile#232]
Please clarify rule that is applied and I will look if it s ok

**Comment by JalilArfaoui** [comment]
On mobile we have a hard-coded `www.` prefix added to detected URLs … We have to check if it breaks some detection … for example with https://chartedesmunicipales.fr/biovancia-avis/

**Comment by MaartenLMEM** [comment]
Quand chrome ou Firefox enlève www. on ne le voit pas
Traité de la façon suivante : en tant qu(appli la regex match soit sur ce que j'ai lu, soit sur www.
Trouvera amélioration supplémentaire avec https://github.com/dis-moi/backend/issues/429

**Comment by JalilArfaoui** [comment]
Solved in #233
