### ISSUE TITLE
LMEL UIs rebranding : Adapt texts

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/mobile#240]
# Onboarding

## Screen 1 

Merci d'avoir téléchargé 
l'application Le Même en Local

S'il existe une alternative locale, vous le saurez. 

- Sans publicité 
- Respecte votre privée
- Open source

**Notes :** 
- Dans cet écran il n'est sans doute pas utile de mettre les logos des contributeurs. 
- Pour les mentions sans publicité, vie privée et open source, on pourra s'inspirer du design du nouveau site web.

**Comment by prk-dismoi** [comment]
![image](https://user-images.githubusercontent.com/80406294/134870566-770e3456-f58c-47dd-9594-97d3a0467f51.png)
let me know.

**Comment by prk-dismoi** [comment]
> Pour les mentions sans publicité, vie privée et open source, on pourra s'inspirer du design du nouveau site web.

![image](https://user-images.githubusercontent.com/80406294/134871186-efd9855d-0c61-4cd4-8344-b3d0bc80fcb5.png)

celui ci?

**Comment by MaartenLMEM** [comment]
Merci. 
En voyant le résultat quelques remarques et idées, à discuter  :

1. `Merci d'avoir téléchargé l'application Le Même en local `
= Message de base secondaire, la police texte la plus basique me semble donc plus adapté.  

2. `S'il existe une alternative locale, vous le saurez. `
Ce message rappelle le à quoi ça lui sert il a téléchargé. Il remet un peu de jus dans la jauge de confiance et de patience de l'internaute. Mais il n'est pas nouveau. 

3. Est-ce qu'on ne pourrait pas aller plus loin en parlant de la cause, le pourquoi ? 
Ce qui donnerait : 

```
`Vous avez téléchargé l'application Le Même en local : `
 **`S'il existe une alternative locale, vous le saurez. `**
 
 
Merci pour votre participation à ce projet qui permet 
de soutenir le local en France et dans ses régions. 

Cette application est :
- Sans publicité 
- Respecte votre vie privée
- Open source
- et encore en construction : n'hésitez pas à nous faire part de vos expériences.
```

**Comment by prk-dismoi** [comment]
![image](https://user-images.githubusercontent.com/80406294/134882148-2ae9df67-f43a-407c-abca-d58f76fd5398.png)

**Comment by MaartenLMEM** [comment]
I find it good. @KaliviArf @J-oh-n , any remark on the text ?

**Comment by MaartenLMEM** [comment]
New text proposal following a talk with Karène & John : 

```
Bienvenu.e sur Le Même en Local : S’il existe une meilleure alternative locale, vous le saurez.

Merci pour votre engagement pour le local en France et dans ses régions. 

Cette application est :
- sans publicité
- open source 
- respectueuse de votre vie privée
```

**Comment by prk-dismoi** [comment]
![image](https://user-images.githubusercontent.com/80406294/134943704-0270dfe1-7aa6-47b0-9c79-45ac766a3685.png)

**Comment by MaartenLMEM** [comment]
Ca me parait bien comme ça : le côté engagé est vachement mis en valeur : engagement du consommateurs et nos engagements.
