### ISSUE TITLE
LMEL rebrand - increase contributor description size

### ISSUE THREAD

**Issue by prk-dismoi** [dis-moi/mobile#241]
@maarten we need a 4 lines description for these 2 accounts, the current descriptions are too short and not very elegant on the PR preview. LME Ile de France / LME Bretagne.

Current versions:

IDF: "Alternatives en région Île-de-France aux offres que vous consultez en ligne !"

Bretagne: "Des alternatives bretonnes ou des bons plans près de chez vous en Bretagne !"

**Comment by prk-dismoi** [comment]
4 lines:
![image](https://user-images.githubusercontent.com/80406294/134872556-d993f440-8fa6-4e86-8a79-31d5d59d1188.png)

2 lines: 
![image](https://user-images.githubusercontent.com/80406294/134872606-4603172f-6ddc-459c-a7fd-0e0544f66be1.png)

**Comment by MaartenLMEM** [comment]
I understand the issue is about global UI coherence on mobile.
But from user point of view, on mobile as on web page, I do not think making longer sentences will help him/her to scan different profiles and to understand why they are different one from each other ; moreover if there all same from one profil to another. 

As a result, I see more an UI adaptation on mobile as a solution here : height should fit to text lenght.  

+ FYI Karène is working on descriptions.

**Comment by prk-dismoi** [comment]
Thanks. Though we had formal guidelines in terms of character lengths for the description and these were not in line. If not, what you say make sense, I will amend designs for the images for John and share again.

**Comment by prk-dismoi** [comment]
![image](https://user-images.githubusercontent.com/80406294/134910615-39ca9f01-0f39-456a-a61b-fe399db15379.png)

**Comment by prk-dismoi** [comment]
![image](https://user-images.githubusercontent.com/80406294/134910931-363e4190-5649-4033-8dfd-57e11432d83b.png)

**Comment by MaartenLMEM** [comment]
- Discuté avec Erick : besoin d'aérer sans doute d'autaut qu'on n'a pas besoin de voir le 3ème éléments de suite.

On pourrait mettre : 
- Plus d'espace en haut et en bas de chaque boîte, au dessus du titre et sous un exemple réel, en gardant le contenu centré verticalement 
- Plus d'espace entre la description et le lien `voir un exemple`

**Comment by prk-dismoi** [comment]
![image](https://user-images.githubusercontent.com/80406294/135068854-3f0b1412-3c99-45a7-9d8e-9bbd2ae9d1ab.png)

@MaartenLMEM see new version with more padding. Check also reinclusion of a minified rooster in the logo as a test.
